# RabbitMQ Configuration File

# Memory Management
vm_memory_high_watermark.relative=0.6

# Disk Space Management
disk_free_limit.absolute =2GB

# SSL/TLS Configuration
ssl_options.verify = verify_none

# Management plugin
management.tcp.port =15672

# Logging
log.file.level = info
log.console = true
log.console.level = info